### ISSUE TITLE
Change default query operator

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#104]
The default operator for fulltext seems to be 'OR'. This should be 'AND.' If I search 'piano flute' I will want something with both piano and flute, not piano or flute.

**Comment by agpar** [comment]
It's a little more nuanced than that. We can set it so it ANDS up to a certain query length, then allows a small amount of OR'ing. I had set it to OR very early (always), since we had so few docs, but we can change that now.

I'm thinking for 2 terms or less, we require all terms. For 3 terms or more, we allow one of the terms to be missing. How does that sound?

**Comment by ahankinson** [comment]
Sounds good

**Comment by agpar** [comment]
Do you want me to try to get these changes on to deployment today? Asking since I told you I wouldn't touch it this week.

**Comment by ahankinson** [comment]
No, I think it's best if we don't touch it now. After tomorrow we can roll out all the new things

**Comment by agpar** [comment]
The change I described above has been implemented. faa3f00611328a6b2c090baf9850ed90d2df3ace

**Comment by ahankinson** [comment]
Have you deployed it yet?

**Comment by agpar** [comment]
Should have!
