### ISSUE TITLE
Process remote_urls so they are always the same.

### ISSUE THREAD

**Issue by agpar** [DDMAL/misirlou#11]
Should implement a method that makes sure all remote_urls start with `http[s]?://` and end with a `/` so that I don't end up missing duplicates based on small technicalities.

Related to #9

**Comment by wabain** [comment]
I'm pretty busy today, but I want to get down my thoughts on this quickly. Hope it makes sense! (I also have thoughts about some of the other issues which I'll get to tomorrow.)

"Technicalities" really is the right word here, because there's nothing in the [relevant standards](http://tools.ietf.org/html/rfc3986) that says that e.g. a URL with and without a trailing slash are the same. So in a sense which I think probably only matters theoretically, doing this is wrong. The practical worry that I have is that some sites might only serve the manifests with a trailing slash and some without. Same with HTTP/HTTPS. So there's no one right canonical form.

Another question: How should this interact with redirects?

**Comment by ahankinson** [comment]
If you ensure [de-dupe](https://cwiki.apache.org/confluence/display/solr/De-Duplication) on the manifest field only, you would remove the possibility of having the same manifest twice in your index, which is what I think you really want.

**Comment by agpar** [comment]
I also want to avoid having a manifest twice in the database. And I'd like to update an existing manifest (call its .save() method so that its update date is changed) rather than delete and create a new one when a manifest is imported for the nth time.

**Comment by ahankinson** [comment]
Nah. Don't bother with updating.

**Comment by agpar** [comment]
Well - it's kind of already done except for doing something to make sure they way I'm comparing urls is fuzzier than 'exact string match'.

If you try to import a url now, it will look if we already have a manifest with that exact url, then call .save() on it and re-index it from the remote.

The idea here is that http://[domain d]/[manifest m] will always have the same uuid in our indexes.

**Comment by agpar** [comment]
Or, if you guys think its of no value to doing this I can remove it. Then we'd just have a different Manifest in the DB for every Manifest that's ever been successfully imported, including duplicates if it was imported more than once.

I thought it would be useful to try to keep the ids consistent and keep the DB empty of any duplicate information - but since we only ever intend to serve search results, I can see how it isn't necessary. And I had no idea that a trailing slash would not necessarily return the same information. If it really is hard to rely on extremely similar urls being the same, then I suppose there's not a lot that _can_ be done.

The de-duping stuff for solr solves the issue on that end though.

**Comment by ahankinson** [comment]
Solr regex queries might be useful here. Define a regex that takes into account http/s and trailing slash, then search for that. If anything comes back, you know you've got a duplicate URL.

http://www.openjems.com/solr-regex-tutorial/

**Comment by wabain** [comment]
I think this all sounds okay to me. What I was really worried about was the URLs that are actually requested getting processed. Doing fuzzy matching sounds fine.

**Comment by agpar** [comment]
Oh duh here's the solution. Since each manifest must have an  `@id` field with the url where it's published, we'll just call that the 'definitive' remote_url for the object. So the trailing slash and schema differences shouldn't even matter - as long as its actually the same manifest at http and https and with or without the trailing slash, it will have the same `@id`

**Comment by agpar** [comment]
This has been fixed by taking the `@id` attribute of a manifest and treating that as the cannon representation of the manifests url.

**Comment by wabain** [comment]
Sorry to nitpick, but what happens if a manifest gets uploaded with an `@id` that points to an existing manifest that's hosted somewhere else? I can imagine that happening if someone decided to make a local copy or something. Would the original manifest be overwritten? I don't know how much we should care about that, but maybe it's worth deduping by the hostname of the URL we're actually dereferencing combined with the `@id` or something?

**Comment by ahankinson** [comment]
Manifests shouldn't get uploaded, right? They should only be dereferenced, so they will only ever really exist at a remote location.

**Comment by wabain** [comment]
Right, "uploaded" is imprecise. I guess what I worry about is the indexed description, etc. getting overwritten.
