### ISSUE TITLE
Stemming

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#110]
Searching for "Cister" I would expect to get this as a suggested result:

https://musiclibs.net/manifests/13c0ca20-7414-47f0-ac9b-2f14d85be0b6?q=Cister

but it finds nothing. ("The letters! They do nothing!")

**Comment by agpar** [comment]
The issue here is that the solr spell checker will only make a maximum of 2 edits to a word as a spellcheck. We have a suggester that would handle this well (which I spent this morning getting very upset with), but we need to integrate it into the front end. 

Type-ahead style suggestions like on google or elvis database would be ideal.

https://dev.musiclibs.net/suggest/?q=cister

Stemming exists on the tokens that are saved when their language is known (since stemming is language sensitive). For instance, a search `Cistercien` does indeed pull up documents with `cistercienne`, `cistercien` and `cisterciennes` in them.

**Comment by agpar** [comment]
Could we assign @belljustin to writing a frontend widget for displaying these results as you type?

**Comment by agpar** [comment]
We have (on dev.musiclibs.net) a type ahead feature that suggests words based on prefix, and suggests from the pool of title and labels based on phrase prefix.

**Comment by ahankinson** [comment]
Looks good, but I need down-arrow selection. :)

**Comment by agpar** [comment]
The suggestion feature has been merged into master, and the solr index is being rebuilt at this very moment.
