### ISSUE TITLE
Search bugginess on client-side

### ISSUE THREAD

**Issue by wabain** [DDMAL/misirlou#27]
Some TODOs for me:

When I encounter an error in a search request, I end up resetting the pagination of the search results, so that if `Retry` gets clicked then the _first_ page of results gets requested and appended to whatever results were already loaded.

Also, there are race conditions around the order responses come in. When a response returns, it wipes out whatever was previously loaded. This means, for instance, that if you clear the search while a request is pending, when that request resolves its query will be set as the search. (This also probably interacts badly with pagination, now that I think about it.)

**Comment by agpar** [comment]
I know we fixed the race conditions on the responses, do @belljustin or @jeromepl know if the error handling issue persists?

**Comment by jeromepl** [comment]
This made me find out that there is currently an issue with the "Retry" button. After fixing it I will be able to check if the error handling works.

**Comment by jeromepl** [comment]
I have found that there are 2 "Retry" buttons in the code. One is in the search results heading and now works properly. The other is in the followup actions and it seems like it would never be rendered.

The conditions for the second button to appear are as follow: 
1 - The current search value is not null (search.current.value)
2 - The results size is bigger than 0 (search.current.value.results.size)
3 - The status of the search is "error" (search.current.status)

I have not been able to satisfy those three conditions at once and am now considering removing this part of the code.

@lexpar or @belljustin do you know if it is possible for the current search value to not be null AND for the search to have and "error" status?

From what I see, results to be displayed when there is an error are put in the "stale" field instead of "current". I thus don't think there can be results in current when the search returns an error.

**Comment by agpar** [comment]
I'm afraid I can't help... I've not looked at the procedure for making and caching searches on the frontend.

**Comment by wabain** [comment]
I'm not sure if it's reachable given the bugs, but the intent was for it to show up when there was an error requesting a page of results subsequent to the first.

**Comment by jeromepl** [comment]
Alright, so I have determined that the code is still reachable. The second button is shown when trying to load more results but an error occurs. I am working on fixing it at the moment. Currently, the first page is reloaded when pressing "Retry" instead of the next page.
