### ISSUE TITLE
Weird spell correction

### ISSUE THREAD

**Issue by wabain** [DDMAL/misirlou#28]
@lexpar, any idea why this is happening?

![screen shot 2016-01-21 at 5 56 54 pm](https://cloud.githubusercontent.com/assets/7651435/12497235/857b6200-c068-11e5-96af-373fdee5aca6.png)

**Comment by agpar** [comment]
It might be because I'm just sending you the first collation as a spell check, and the query 'r e c en si on' would be extremely popular, as it contains the extremely common words 'en', 'si' and 'on' (three languages worth of high popularity!). 

Maybe I can work out something more appropriate. There is an option to turn off spellcheck if the query returns >0 results, as well.

Can you send me the urls of these manifests so I can import them myself and have a look.

**Comment by ahankinson** [comment]
Is there an n-gram or edge n-gram tokenizer on that field in Solr? That might cause this. 

https://cwiki.apache.org/confluence/display/solr/Tokenizers#Tokenizers-N-GramTokenizer

**Comment by agpar** [comment]
No. The spell check field is a copy destination for all the language individuated text fields, and it just applies a lower case and filter factory.

There exists a [PreAnalyzed field](https://wiki.apache.org/solr/PreAnalyzedField) which would be much better here, as it would carry over the correct stop words from the languages that are being aggregated here. I had trouble getting it to work right the last time I tried, but should give it another go.

**Comment by agpar** [comment]
This is fixed on the new-validator branch.
