### ISSUE TITLE
Fix diva viewer bug

### ISSUE THREAD

**Issue by jeromepl** [DDMAL/misirlou#78]
Currently, after viewing a result then clicking on a new one and coming back to the first one, the diva viewer becomes un-scrollable and the diva toolbar duplicates. When repeating those steps, even more toolbars get appended.

Here is what I know about this bug at the moment:
- It happens only when viewing a manifest that has been previously loaded (it exists in the redux store under manifests -> [manifestId] )
- Usually, the diva component is Unmounted, and a new one is remounted when clicking a new result. However, when this bug occurs, the component is not unmounted. Instead, its props are updated. (Note that the 'destroy' method of the diva instance is still called in that case)

**Comment by agpar** [comment]
It looks like diva just does nothing to clean up that toolbar when you destroy it. The reason it disappears _sometimes_ is because when you select a new manifest, you are instantiating a diva component with a before unseen set of properties, so react unmounts the current component and makes a new one (effectively clearing out all the divs). When you look at a previously viewed manifest, you are instanciating a diva component with a set of properties that previously existed. React must have that component cached in some way (based on its properties), so it does not unmount the current component, just applies a diff to it. This results in the doubled up toolbar.

**Comment by agpar** [comment]
The root of the problem is that diva renames its divs every time you instantiate a diva viewer. So the toolbar is originally called `1-diva-tools`, then the second one you create is called `2-diva-tools`, etc. So when react does the diff between the current `2` diva viewer and the cached `1` diva viewer, it sees these two divs that it have different ID's and decides that they are unrelated, so keeps both.

**Comment by agpar** [comment]
Just to be clear, this is fixed, gut there might be good reason to see if we can pull the manifest request out of the page load so we can avoid instantiating multiple diva viewers.
