### ISSUE TITLE
Search results label is duplicated

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#84]
In the search results, the title and the label shown seem to just duplicate each other. 

I know there is probably a limited amount of room for this particular view, so I would like to see the 'Label' field changed to show the source of the manifest (Internet Archive, Vatican, etc.)

**Comment by agpar** [comment]
Can you give an example search query on dev where this happens? `title` is not a top level key, so if a query matches on `label` and `title` its likely because the library included `title` as a metadata key. What I'm getting at here is that they are different things.

**Comment by ahankinson** [comment]
https://dev.musiclibs.net/?q=klavier

**Comment by agpar** [comment]
Oh, you mean the label being a hyperlink and the highlight of the label underneath? That's the redundancy right?

**Comment by ahankinson** [comment]
Perhaps it could be styled a bit like Google's results, where the source URL is given just below the title.

I don't think we should include the URL to the manifest, but perhaps something like "Source: archivelabs.org" ?

**Comment by ahankinson** [comment]
Yeah -- it looks like the title and the highlighted bit is the same thing.

**Comment by agpar** [comment]
Okay, I misunderstood then. They would be the same thing in that case.

Should we remove the highlighting in the results? Or only in the case of the 'label' field (which will always be the same as the hyperlink to view the result).

We can display the url of the library. Although, that might be a little bit tricky since a lot of libraries have different hostnames for the iiif services than the actual library. It would be between choosing whether to just grab the netloc of the manifest (iiif.harvard.edu or something similar), or trying to figure out a clever way (or tailored mapping) to discern this.

**Comment by ahankinson** [comment]
I think just the hostname of the IIIF host would be fine. I don't think we need to remove the highlighted area, just put something like: "Source: iiif.harvard.edu" directly under the title so that it's clear that they're coming from different places.

I'm thinking of something like the green URL text in Google searches: https://www.google.ca/search?q=klavier

**Comment by agpar** [comment]
Ok, sounds good :+1:

**Comment by agpar** [comment]
![image](https://cloud.githubusercontent.com/assets/9021839/16265993/7f9369ae-3850-11e6-8ddf-0ab1c700c113.png)

Like this?

**Comment by ahankinson** [comment]
Beautiful! 🎉

**Comment by agpar** [comment]
Related: I'm fixing it so that if a highlight is on the label, it will just highlight the hyperlink rather than include the 'label' field in the body of the result.
![image](https://cloud.githubusercontent.com/assets/9021839/16268889/249b48ec-385e-11e6-9353-02078d5ddd96.png)

**Comment by agpar** [comment]
This should be all wrapped up.

**Comment by ahankinson** [comment]
:shipit:
